# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-poc
  region: eu-west-1

vpc:
  cidr: 10.29.7.0/24

nodeGroups:
  - name: ng-1
    labels: { role: back }
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    ssh: # import public key from file
      publicKeyPath: ~/.ssh/id_rsa.pub
